services:
  phpgit:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/app

  test:
    build:
      dockerfile: Dockerfile.test
    volumes:
      - ./:/app

  bench:
    build:
      dockerfile: Dockerfile.bench
    volumes:
      - ./:/app
