services:
  php:
    build:
      dockerfile: Dockerfile
    entrypoint: ["php", "src/app.php"]
    volumes:
      - ./:/app

  test:
    build:
      dockerfile: Dockerfile.test
    volumes:
      - ./:/app
